// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByEMiXoLwNtHxDfLEDNt_45E2tIhWOpF4',
    appId: '1:697738524423:web:5c213d39c5c59c10a2f7a2',
    messagingSenderId: '697738524423',
    projectId: 'controlgastosapp-9ce8d',
    authDomain: 'controlgastosapp-9ce8d.firebaseapp.com',
    storageBucket: 'controlgastosapp-9ce8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJXStHBHfQZY3So-SOXi7qH1gsNotIn3U',
    appId: '1:697738524423:android:229887b7e0917146a2f7a2',
    messagingSenderId: '697738524423',
    projectId: 'controlgastosapp-9ce8d',
    storageBucket: 'controlgastosapp-9ce8d.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByEMiXoLwNtHxDfLEDNt_45E2tIhWOpF4',
    appId: '1:697738524423:web:b96a1e0261b7ee93a2f7a2',
    messagingSenderId: '697738524423',
    projectId: 'controlgastosapp-9ce8d',
    authDomain: 'controlgastosapp-9ce8d.firebaseapp.com',
    storageBucket: 'controlgastosapp-9ce8d.appspot.com',
  );
}
